// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeEF13226HZKNPAFCDeKYvJCvuGqo0eu8',
    appId: '1:510679639833:web:de353a7551447620990788',
    messagingSenderId: '510679639833',
    projectId: 'nice-c1bd2',
    authDomain: 'nice-c1bd2.firebaseapp.com',
    storageBucket: 'nice-c1bd2.appspot.com',
    measurementId: 'G-G4F4DJM91N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_SSo20GDBmMCWZJygiWCwPM8E06f0a4',
    appId: '1:510679639833:android:915fd0f37a6dd9a9990788',
    messagingSenderId: '510679639833',
    projectId: 'nice-c1bd2',
    storageBucket: 'nice-c1bd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEzB-xDqVmHVKA7Oo_Svz6LeHBUJxylKg',
    appId: '1:510679639833:ios:eedab9dd3946e341990788',
    messagingSenderId: '510679639833',
    projectId: 'nice-c1bd2',
    storageBucket: 'nice-c1bd2.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEzB-xDqVmHVKA7Oo_Svz6LeHBUJxylKg',
    appId: '1:510679639833:ios:eedab9dd3946e341990788',
    messagingSenderId: '510679639833',
    projectId: 'nice-c1bd2',
    storageBucket: 'nice-c1bd2.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeEF13226HZKNPAFCDeKYvJCvuGqo0eu8',
    appId: '1:510679639833:web:3e923207ee5756ea990788',
    messagingSenderId: '510679639833',
    projectId: 'nice-c1bd2',
    authDomain: 'nice-c1bd2.firebaseapp.com',
    storageBucket: 'nice-c1bd2.appspot.com',
    measurementId: 'G-6YMBBR9E4W',
  );
}
